name: Python Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==3.1.1 flask-cors==6.0.0 python-dotenv==1.0.0 pytest
      - name: Run tests
        run: |
          pytest -q
